#!/usr/bin/env bash

MODULE_NAME='Whitelist Unity Systray'

log_module_start


SCHEMA=com.canonical.Unity.Panel
KEY=systray-whitelist

function check_whitelist()
{
    gsettings list-children "$SCHEMA" >/dev/null 2>&1 || return 0
    gsettings get $SCHEMA $KEY | grep -q "\['all'\]"
}

function systray_whitelist_all()
{
    gsettings set $SCHEMA $KEY "['all']"
}

if check_whitelist; then
    log_no_changes
else
    systray_whitelist_all
    log_module_end
fi
