#!/usr/bin/env bash

BOOTSTRAP_DIR=$(dirname $BASH_SOURCE)
LIBRARY_DIR=$BOOTSTRAP_DIR/lib
MODULES_ACTIVE_DIR=${OVERRIDE_MODULES_DIR:-$BOOTSTRAP_DIR/modules}

function check_has_bash4
{
    ${BASH4:-bash} --version | grep -q "GNU bash.*version 4" || \
        { echo  "ERROR: Bash v4 or newer is required"; exit 1; }
}

function assert_not_at_home()
{
    case "$(readlink -f "$BOOTSTRAP_DIR")" in
        /home/*)
        { echo  "Do not run from under the home directory"; exit 1; }
    esac
}

function source_library()
{
    for file in $LIBRARY_DIR/*.sh
    do
        source $file EXPORT || { echo "Library error" && exit 1; }
    done
}

function run_module()
{
    local file="$1"
    if is_exec "$file"
    then
        ( cd "$MODULES_ACTIVE_DIR" && ./$(basename $file) )
    fi
}

function run_modules()
{
    if [[ -n $1 ]]
    then
        log_info "Running only these modules: $*"
        for file in "$@"
        do
            run_module $MODULES_ACTIVE_DIR/$file
        done
    else
        while read line
        do
            run_module "$MODULES_ACTIVE_DIR/$line"
        done < $MODULES_ACTIVE_DIR/modules.enabled
    fi
}

function main()
{
    check_has_bash4
    assert_not_at_home
    source_library
    run_modules "$@"
}


main "$@"
