#!/usr/bin/env bash

# Find the root dir
dir=$(dirname ${BASH_SOURCE[0]})
command cd "$dir"
while [[ 1 ]]
do
    [[ -e $dir/bootstrap ]] && break
    [[ $dir == '/' ]] && break
    command cd ..
    dir=$(pwd)
done

$dir/bootstrap --list | awk -F' :: ' '/::/{print "* " $2}'
